# Generated by Django 3.1.4 on 2021-02-27 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(default='', max_length=255)),
                ('description', models.TextField()),
                ('Img', models.ImageField(upload_to='photos')),
                ('Img2', models.ImageField(upload_to='photos')),
                ('Img3', models.ImageField(upload_to='photos')),
                ('Img4', models.ImageField(upload_to='photos')),
                ('Img5', models.ImageField(upload_to='photos')),
                ('Img6', models.ImageField(upload_to='photos')),
                ('Img7', models.ImageField(upload_to='photos')),
                ('Img8', models.ImageField(upload_to='photos')),
                ('Img9', models.ImageField(upload_to='photos')),
                ('Img10', models.ImageField(upload_to='photos')),
                ('video', models.FileField(upload_to='videos')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.theme')),
            ],
        ),
    ]
