# Generated by Django 3.1.4 on 2021-02-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210227_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='post_slug',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='slug',
            new_name='theme_slug',
        ),
    ]
